### ISSUE TITLE
Disable ScoreHud

### ISSUE THREAD

**Issue by KingRainbow44** [JackMD/ScoreHud#137] opened 2019-08-31 22:26 UTC
Is it possible to disable scorehud in worlds we choose? I have a skywars plugin and ScoreHud is interfering with its scoreboard.

**Comment by JackMD** [comment] 2019-09-15 11:34
Duplicate of #125 and #26

**Closed by JackMD** 2019-09-15 11:34 UTC

**Comment by KingRainbow44** [comment] 2019-09-16 14:01
No, not like that. I mean, like COMPLETELY. Not just showing a blank ScoreHud. If you need a video explanation on what I mean, then please respond to this.
